# Generated by Django 6.0.6 on 2026-06-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
