# Generated by Django 6.0.6 on 2026-07-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0003_genre_user_test_count_views_test_genre_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='image',
            field=models.ImageField(null=True, upload_to='test_images/'),
        ),
    ]
