# Generated by Django 6.0.6 on 2026-07-10 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0004_alter_test_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='tests_app.question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='tests_app.test')),
            ],
        ),
    ]
